// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCRsTEDqi5HN0ncurjzSPSMPO2elwLpQwo',
    appId: '1:421553013539:web:c262243ca3127ff53d0296',
    messagingSenderId: '421553013539',
    projectId: 'blooddonation-97cc7',
    authDomain: 'blooddonation-97cc7.firebaseapp.com',
    storageBucket: 'blooddonation-97cc7.appspot.com',
    measurementId: 'G-JMNMZXPJBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdZbBe4YxktlQGOkCSr3VqX8lagW6bys4',
    appId: '1:421553013539:android:886498ab2fe1e21b3d0296',
    messagingSenderId: '421553013539',
    projectId: 'blooddonation-97cc7',
    storageBucket: 'blooddonation-97cc7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCW0FSv7PBjyA4LYShSRT3-YVv73_65x10',
    appId: '1:421553013539:ios:019309e7f96e726a3d0296',
    messagingSenderId: '421553013539',
    projectId: 'blooddonation-97cc7',
    storageBucket: 'blooddonation-97cc7.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCW0FSv7PBjyA4LYShSRT3-YVv73_65x10',
    appId: '1:421553013539:ios:93fd989a9174bc513d0296',
    messagingSenderId: '421553013539',
    projectId: 'blooddonation-97cc7',
    storageBucket: 'blooddonation-97cc7.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
